// Generated by CoffeeScript 1.9.2
(function() {
  var app, coffee, express, filename, filenames, fn, fs, i, len;

  express = require('express');

  fs = require('fs');

  coffee = require('coffee-script');

  app = module.exports = express();

  app.use(express["static"](__dirname + "/public"));

  app.get('/', function(req, res) {
    return fs.readFile(__dirname + "/index.html", 'utf8', function(err, text) {
      res.contentType('text/html');
      return res.send(text);
    });
  });

  app.get('/test', function(req, res) {
    return fs.readFile(__dirname + "/test.html", 'utf8', function(err, text) {
      res.contentType('text/html');
      return res.send(text);
    });
  });

  filenames = ['legs', 'simulation'];

  fn = function(filename) {
    return app.get("/" + filename + ".js", function(req, res) {
      return fs.readFile(__dirname + "/" + filename + ".coffee", 'utf8', function(err, text) {
        res.contentType('application/javascript');
        return res.send(coffee.compile(text));
      });
    });
  };
  for (i = 0, len = filenames.length; i < len; i++) {
    filename = filenames[i];
    fn(filename);
  }

  app.listen(3000);

  console.log("Express server listening on port in " + app.settings.env + " mode");

}).call(this);
